theme: jekyll-theme-hacker
title: Mariano's Pentest Blog
description: Writeups, notes and bug bounty findings
show_downloads: false
url: "https://marianoja.github.io"
baseurl: "/hacking-blog"
permalink: /:year/:month/:day/:title.html
